baseurl: https://3rickDJ.github.io/vive-codigo-HugoMigration
title: ViveCodigo.org
language: es
theme: hello-4s3ti
paginate: 10
# paginatePath: /blog/

author:
  name: MakingDevs

disqusShortname: vivecodigo

copyright: "All rights reserved"

permalinks:
  blog: blog/:year/:month/:day/:title/

blackfriday:
  hrefTargetBlank: true

taxonomies:
  tag: tags
  category: categories

params:
  contentTypeName: blog
  # Day formats
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"

  enableSharingButtons: false
  # metadata description
  description: "El podcast para desarrolladores de software."
  keywords: "programming code languages frameworks podcast video learning makingdevs"
  # home page
  homeTitle: "ViveCodigo.org"
  homeSubtitle: "El podcast para desarrolladores de software."
  # backgroundImage @ home
  backgroundImage: "images/bg_wall.png"
  backgroundEffects: true
  # theme dark/light
  enableThemeToggle: true
  # home posts
  showPosts: true
  # hideReadMore: true
  # showReadingTime: false

  ## footer
  footer:
    trademark: true
    copyright: true
    author: true
    socialIcons: true
    # bottomText:
    #   - "Powered by <a href=\"http://gohugo.io\">Hugo</a>"

  logo:
    logoMark: ">"
    logoText: "$vive-codigo"
    logoCursorColor: "#67a2c9"
    logoCursorAnimate: "6s"

  fontAwesome:
    kitURL: "https://kit.fontawesome.com/f3a7e69c00.js"

  social:
    - name: "twitter"
      url: "https://twitter.com/ViveCodigo"
    - name: "vimeo"
      url: "https://vimeo.com/makingdevs"
      icon: "fa-brands fa-vimeo-v"
    - name: "iTunes"
      url: "https://itunes.apple.com/mz/podcast/vivecodigo.org-podcast/id722889939"
      icon: "fa-brands fa-itunes-note"

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog

markup:
  goldmark:
    renderer:
      unsafe: true
